import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import Sidebar from "./_components/sidebar";
import TeamSidebar from "./_components/teamSidebar";
import Navbar from "./_components/navbar";
import { SessionProvider } from "next-auth/react";
import S3GrantsProvider from "../_lib/s3GrantsProvider";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<SessionProvider>
			<S3GrantsProvider>
				<main className="h-[100vh]">
					<Sidebar />
					<div className="h-full pl-[60px]">
						<div className="flex h-full gap-x-3">
							<TeamSidebar />
							<div className="h-full flex-1">
								<Navbar />
								{children}
							</div>
						</div>
					</div>
				</main>
			</S3GrantsProvider>
		</SessionProvider>
	);
}
